moesifdjango/middleware.py, setup.py
=> Add: Message for Middleware in Django 1.9 and older

moesifdjango/middleware_pre19.py, setup.py
Fixed: Middleware to read request body
Fixed: Metadata debug statement
Update: Bump Version to 1.2.3
=> Fixed: Middleware to read request body

.gitignore, README.md, moesifdjango/middleware.py, moesifdjango/tasks.py, requirements.txt
This is definitely not pressing, but since I developed if for internal usage I think it would be useful for other developers as well.
The whole idea is to add all HTTP requests (updating moesif) in a queue.
=> Adding Celery as a backend

README.md, moesifdjango/middleware.py, moesifdjango/tasks.py
Update: Enabling celery
Update: README documentation
=> Feature celery

moesifdjango/middleware.py
=> Fixed: Merge conflicts

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py
Fixed: Access body after reading from request's data stream
Fixes: Issue #9
=> Fixed: Access request's body/data stream

README.md, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, requirements.txt, setup.py
Add: Capture outgoing requests
Update: Dependencies version
Bump: version to 1.3.4
=> Add: Capture outgoing requests

moesifdjango/middleware.py, moesifdjango/tasks.py, setup.py
Add: Send Batch Events
Bump version to 1.3.7
=> Add: Send Batch Events

moesifdjango/app_config.py, moesifdjango/middleware_pre19.py, setup.py
Refactor: logic to fetch sample rate
=> Refactor: logic to fetch sample rate

requirements.txt, setup.py
Refactor: Update Dependencies
Bump version to 1.4.3
=> Refactor: Update Dependencies

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Add: Transaction Id to Request-Response Headers
Bump version to 1.4.4
=> Add: Transaction Id to Request-Response Headers

.gitignore, README.md, moesifdjango/client_ip.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, moesifdjango/update_users.py, setup.py, tests/manage.py, tests/middleware_pre19_tests/tests.py, tests/middleware_tests/tests.py, tests/settings.py
Add: Unit Test
Add: updateUser function
Add: Support for proxy server where we could not get the ip address
Bump version to 1.4.5
=> Add: Unit Test

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Add: Support for Python 3.4 file imports
Bump version to 1.5.1
=> Add: Support for Python 3.4 file imports

moesifdjango/client_ip.py, setup.py
Fix: Remove Client Ip headers encoding
Bump version to 1.5.2
=> Fix: Remove Client Ip headers encoding

README.md, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, moesifdjango/update_companies.py, moesifdjango/update_users.py, setup.py, tests/middleware_pre19_tests/tests.py, tests/middleware_tests/tests.py
Add: Update company and batch companies functions
Add: Unit test
Bump version to 1.5.3
=> Add: Update company and batch companies functions

README.md, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Add: CompanyId to EventModel
Bump version to 1.5.6
=> Add: CompanyId to EventModel

README.md, requirements.txt
Update: moesifpythonrequest dependency to 0.1.9
Update: README.md (Based on PR #26 comments)
=> Update: moesifpythonrequest dependency to 0.1.9

README.md, tests/middleware_pre19_tests/tests.py, tests/middleware_tests/tests.py
Update: README.md on how to set companyDomain
Update: Tests with companyDomain set when updating company details
=> Update: README.md on how to set companyDomain

README.md, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, requirements.txt, setup.py
Add: LogBody configuration option to remove request and response body
Update: moesifpythonrequest dependency to 0.1.10
Bump version to 1.5.7
=> Add: LogBody configuration option to remove request and response body

moesifdjango/app_config.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Refactor: Application configuration
Bump version to 1.5.8
=> Refactor: Application configuration

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, moesifdjango/tasks.py, requirements.txt, setup.py
Refactor: Application configuration for celery
Update: requirements.txt
Bump version to 1.5.9
=> Refactor: Application configuration for celery

README.md, moesifdjango/middleware.py, moesifdjango/tasks.py, requirements.txt, setup.py
Refactor: Optimize queue initialization for Celery
Refactor: Requirements.txt to support Celery 3.1.25 and above
Add: Required packages
Bump version to 1.5.11
=> Refactor: Optimize queue initialization for Celery

README.md, moesifdjango/app_config.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, requirements.txt, setup.py
Add: Logic to fetch User/Company Sampling percentage
Bump moesifpythonrequest to 0.1.11
Bump version to 1.6.1
=> Add: Logic to fetch User/Company Sampling percentage

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Add: Support for multipart/form-data request body
Bump version to 1.6.3
=> Add: Support for multipart/form-data request body

README.md, requirements.txt, setup.py, tests/middleware_pre19_tests/tests.py, tests/middleware_tests/tests.py
Add: Campaign object to Update User and Company test
Refactor: Update moesifapi version to 1.2.8
Refactor: Update README.md
Bump version to 1.7.1
=> Add: Campaign object to Update User and Company test

requirements.txt, setup.py
Refactor: Update moesifapi version to 1.3.0
Bump version to 1.7.2
=> Refactor: Update moesifapi version to 1.3.0

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, requirements.txt, setup.py
Add: direction and weight field to event
Refactor: Debug message
Refactor: Update moesifapi dependency to 1.3.2
Refactor: Update moesifpythonrequest dependency to 0.2.0
Bump version to 1.7.3
=> Add: direction and weight field to event

moesifdjango/client_ip.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, moesifdjango/parse_body.py, moesifdjango/update_companies.py, moesifdjango/update_users.py, setup.py
Add: Support for gzip body
Refactor: User, Company, and ClientIp as Class
Bump version to 1.7.4
=> Add: Support for gzip body

moesifdjango/app_config.py, moesifdjango/middleware.py, setup.py
Add: Catch exception while getting application config
Refactor: Check if config is not empty before fetching
Refactor: Remove print message
Bump version to 1.7.5
=> Add: Catch exception while getting application config

README.md, moesifdjango/app_config.py, moesifdjango/client_ip.py, moesifdjango/event_mapper.py, moesifdjango/logger_helper.py, moesifdjango/masks.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, moesifdjango/parse_body.py, moesifdjango/tasks.py, moesifdjango/update_companies.py, moesifdjango/update_users.py, setup.py, tests/middleware_pre19_tests/tests.py, tests/middleware_tests/tests.py, tests/settings.py
Add: Support to fetch user Id from authorization header
Add: Helper functions to create event model
Add: Helper functions for config options
Refactor: Add Init method to the class
Refactor: Add Classmethod to the function who doesn't need class instance
Refactor: Test for Django1.9 and above & support for Python 2 and 3
Refactor: Update README.md
Bump version to 1.7.6
=> Refactor: Add Init method to the class

setup.py
=> Fix: Publish version

moesifdjango/job_scheduler.py, setup.py
Refactor: Remove job from the scheduler
Refactor: Bump version to 2.0.1
=> Refactor: Remove job from the scheduler

moesifdjango/logger_helper.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Refactor: Prioritize identify user customer hook
Bump version to 2.0.2
=> Refactor: Prioritize identify user customer hook

moesifdjango/job_scheduler.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Refactor: Scheduler job for every worker
Bump version to 2.0.3
=> Refactor: Scheduler job for every worker

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Add: BASE_URI config option
Bump version to 2.0.4
=> Add: BASE_URI config option

README.md
Refactor: Add MoesifProxy BaseURI to documentation
=> Refactor: Add MoesifProxy BaseURI to documentation

moesifdjango/logger_helper.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Refactor: Support headers attribute for Django 3.2
Refactor: Bump version to 2.0.5
=> Refactor: Support headers attribute for Django 3.2

README.md
Refactor: Add Troubleshooting section in README
=> Refactor: Add Troubleshooting section in README

moesifdjango/moesif_gov.py, requirements.txt, setup.py
to support Governance rule and handle regex invalid pattern.
Related PRs
[1/3]https://github.com/Moesif/moesifapi-python/pull/12
[3/3]https://github.com/Moesif/moesifdjangoexample/pull/27
=> Update moesif api version ..

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Refactor: Update user-agent to the correct version 
Bump version to 2.1.3
=> Refactor: Update user-agent to the correct version

moesifdjango/app_config.py, setup.py
=> Return default if config is not set or empty response is received.

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
Issue: https://github.com/Moesif/moesifasgi/issues/12
Ticket # 183381816
Related PR: [2/2] https://github.com/Moesif/moesifdjangoexample/pull/32
=> fixed incorrect elapsed time duration, and bump up version

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
=> #237402304 fix scheduler restart issue

moesifdjango/block_response_buffer.py, moesifdjango/event_mapper.py, moesifdjango/governance_rule_response.py, moesifdjango/middleware.py, moesifdjango/moesif_gov.py, requirements.txt, setup.py
Related ticket:
[1/3] https://github.com/Moesif/moesifapi-python/pull/14
=> #183253655 : [2/3] Added support for blocked_by

moesifdjango/job_scheduler.py, setup.py
Check the request time against the current time after sending a batch and log in debug mode
=> Check the request time against the current time after sending a batch

README.md, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, requirements.txt, setup.py
Refactor: Event queue size config option default to 1M 
Refactor: Bump moesifpythonrequest to version 0.3.2 
Refactor: Update README.md
Bump version to 2.3.5
- [ x] `Follows` guidelines for `public` repo ?
- [ x] `README` updated, if required ?
- [ x] `Release Version` updated ?
- [x ] `Does NOT` include code from others?  (Unintended consequence of a bad merge) ?
=> #186450397 #186127421 Refactor: Event queue size config option default to 1M

moesifdjango/client_ip.py, moesifdjango/governance_rules.py, moesifdjango/job_scheduler.py, moesifdjango/logger_helper.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, moesifdjango/moesif_gov.py, moesifdjango/update_companies.py, moesifdjango/update_users.py, requirements.txt, setup.py
=> #186810782 change print to logger

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py
=> updated version number in middleware.py

moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, requirements.txt, setup.py
Refactor: Update moesifapi-python and moesifpythonrequest dependencies 
Bump version to 2.3.10 
=> #188414493 Refactor: Update moesifapi-python and moesifpythonrequest dependencies 

moesifdjango/client_ip.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, requirements.txt, setup.py
=> #188481396: update checker for ipv6

README.md, moesifdjango/logger_helper.py, moesifdjango/middleware.py, moesifdjango/middleware_pre19.py, setup.py
=> Update Readme for Gunicorn on MacOS  and slight optimization
